
from flask import Flask
from flask import render_template,request
from langdetect import detect


app = Flask(__name__)

ans = None

@app.route('/')
def index():
    global ans
    return render_template('index.html', text = None, ans = ans)

@app.route('/send', methods=['POST'])
def send():
    text = None
    all_languages_codes =   {
  	'ab': 'Abkhazian',
  	'abk': 'Abkhazian',
  	'aa': 'Afar',
  	'aar':'Afar',
  	'af': 'Afrikaans - Tiếng Afikaans (Tiếng Hà Lan nói ở Nam Phi)',
  	'afr': 'Afrikaans - Tiếng Afikaans (Tiếng Hà Lan nói ở Nam Phi)',
  	'sq': 'Albanian - Tiếng Albania',
  	'alb/sqi*': 'Albanian - Tiếng Albania',
  	'am': 'Amharic',
  	'amh': 'Amharic',
  	'ar': 'Arabic - Tiếng Ả-rập',
  	'ara': 'Arabic - Tiếng Ả-rập',
  	'an': 'Aragonese',
  	'arg': 'Aragonese',
  	'hy': 'Armenian',
  	'arm/hye*': 'Armenian',
  	'as': 'Assamese',
  	'asm': 'Assamese',
  	'ae': 'Avestan',
  	'ave': 'Avestan',
  	'ay': 'Aymara',
  	'aym': 'Aymara',
  	'az': 'Azerbaijani - Tiếng Azerbaijan',
  	'aze': 'Azerbaijani - Tiếng Azerbaijan',
  	'ba': 'Bashkir',
  	'bak': 'Bashkir',
  	'eu': 'Basque - Tiếng Basque',
  	'baq/eus*': 'Basque - Tiếng Basque',
  	'be': 'Belarusian - Tiếng Belarus',
  	'bel': 'Belarusian - Tiếng Belarus',
  	'bn': 'Bengali - Tiếng Bengal',
  	'ben': 'Bengali - Tiếng Bengal',
  	'bh': 'Bihari',
  	'bih': 'Bihari',
  	'bi': 'Bislama',
  	'bis': 'Bislama',
  	'bs': 'Bosnian - Tiếng Bosnia',
  	'bos': 'Bosnian - Tiếng Bosnia',
  	'br': 'Breton',
  	'bre': 'Breton',
  	'bg': 'Bulgarian - Tiếng Bulgaria',
  	'bul': 'Bulgarian - Tiếng Bulgaria',
  	'my': 'Burmese',
  	'bur/mya*': 'Burmese',
  	'ca': 'Catalan - Tiếng Catalan',
  	'cat': 'Catalan - Tiếng Catalan',
  	'ch': 'Chamorro',
  	'cha': 'Chamorro',
  	'ce': 'Chechen',
  	'che': 'Chechen',
  	'zh': 'Chinese - Tiếng Trung Quốc phổ thông',
  	'zh-cn': 'Chinese (Simplified) - Tiếng Trung (Giản thể)',
  	'zh-tw': 'Chinese (Traditional) - Tiếng Trung (Phồn thể)',
  	'chi/zho*': 'Chinese - Tiếng Trung Quốc phổ thông',
  	'cu': 'Church Slavic; Slavonic; Old Bulgarian',
  	'chu': 'Church Slavic; Slavonic; Old Bulgarian',
  	'cv': 'Chuvash',
  	'chv': 'Chuvash',
  	'kw': 'Cornish',
  	'cor': 'Cornish',
  	'co': 'Corsican',
  	'cos': 'Corsican',
  	'hr': 'Croatian - Tiếng Croatia',
  	'scr/hrv*': 'Croatian - Tiếng Croatia',
  	'cs': 'Czech - Tiếng Séc',
  	'cze/ces*': 'Czech - Tiếng Séc',
  	'da': 'Danish - Tiếng Đan Mạch',
  	'dan': 'Danish - Tiếng Đan Mạch',
  	'dv': 'Divehi; Dhivehi; Maldivian',
  	'div': 'Divehi; Dhivehi; Maldivian',
  	'nl': 'Dutch - Tiếng Hà Lan',
  	'dut/nld*': 'Dutch - Tiếng Hà Lan',
  	'dz': 'Dzongkha',
  	'dzo': 'Dzongkha',
  	'en': 'English - Tiếng Anh',
  	'eng': 'English - Tiếng Anh',
  	'eo': 'Esperanto',
  	'epo': 'Esperanto',
  	'et': 'Estonian - Tiếng Estonia',
  	'est': 'Estonian - Tiếng Estonia',
  	'fo': 'Faroese',
  	'fao': 'Faroese',
  	'fj': 'Fijian',
  	'fij': 'Fijian',
  	'fi': 'Finnish - Tiếng Phần Lan',
  	'fin': 'Finnish - Tiếng Phần Lan',
  	'fr': 'French - Tiếng Pháp',
  	'fre/fra*': 'French - Tiếng Pháp',
  	'gd': 'Gaelic; Scottish Gaelic',
  	'gla': 'Gaelic; Scottish Gaelic',
  	'gl': 'Galician',
  	'glg': 'Galician',
  	'ka': 'Georgian - Tiếng Georgia',
  	'geo/kat*': 'Georgian - Tiếng Georgia',
  	'de': 'German - Tiếng Đức',
  	'ger/deu*': 'German - Tiếng Đức',
  	'el': 'Greek, Modern (1453-) - Tiếng Hy Lạp',
  	'gre/ell*': 'Greek, Modern (1453-) - Tiếng Hy Lạp',
  	'gn': 'Guarani',
  	'grn': 'Guarani',
  	'gu': 'Gujarati - Tiếng Gujarat',
  	'guj': 'Gujarati - Tiếng Gujarat',
  	'ht': 'Haitian; Haitian Creole',
  	'hat': 'Haitian; Haitian Creole',
  	'ha': 'Hausa',
  	'hau': 'Hausa',
  	'he': 'Hebrew - Tiếng Do Thái',
  	'heb': 'Hebrew - Tiếng Do Thái',
  	'hz': 'Herero',
  	'her': 'Herero',
  	'hi': 'Hindi - Tiếng Hindi',
  	'hin': 'Hindi - Tiếng Hindi',
  	'ho': 'Hiri Motu',
  	'hmo': 'Hiri Motu',
  	'hu': 'Hungarian - Tiếng Hungary',
  	'hun': 'Hungarian - Tiếng Hungary',
  	'is': 'Icelandic - Tiếng Iceland',
  	'ice/isl*': 'Icelandic - Tiếng Iceland',
  	'io': 'Ido',
  	'ido': 'Ido',
  	'id': 'Indonesian - Tiếng Indonesia',
  	'ind': 'Indonesian - Tiếng Indonesia',
  	'ia': 'Interlingua (International Auxiliary Language Association)',
  	'ina': 'Interlingua (International Auxiliary Language Association)',
  	'ie': 'Interlingue',
  	'ile': 'Interlingue',
  	'iu': 'Inuktitut',
  	'iku': 'Inuktitut',
  	'ik': 'Inupiaq',
  	'ipk': 'Inupiaq',
  	'ga': 'Irish - Tiếng Ai-len',
  	'gle': 'Irish - Tiếng Ai-len',
  	'it': 'Italian - Tiếng Ý',
  	'ita': 'Italian - Tiếng Ý',
  	'ja': 'Japanese - Tiếng Nhật',
  	'jpn': 'Japanese - Tiếng Nhật',
  	'jv': 'Javanese',
  	'jav': 'Javanese',
  	'kl': 'Kalaallisut',
  	'kal': 'Kalaallisut',
  	'kn': 'Kannada',
  	'kan': 'Kannada',
  	'ks': 'Kashmiri',
  	'kas': 'Kashmiri',
  	'kk': 'Kazakh - Tiếng Kazakh ',
  	'kaz': 'Kazakh - Tiếng Kazakh',
  	'km': 'Khmer - Tiếng Khmer',
  	'khm': 'Khmer - Tiếng Khmer',
  	'ki': 'Kikuyu; Gikuyu',
  	'kik': 'Kikuyu; Gikuyu',
  	'rw': 'Kinyarwanda',
  	'kin': 'Kinyarwanda',
  	'ky': 'Kirghiz',
  	'kir': 'Kirghiz',
  	'kv': 'Komi',
  	'kom': 'Komi',
  	'ko': 'Korean - Tiếng Hàn Quốc',
  	'kor': 'Korean - Tiếng Hàn Quốc',
  	'kj': 'Kuanyama; Kwanyama',
  	'kua': 'Kuanyama; Kwanyama',
  	'ku': 'Kurdish',
  	'kur': 'Kurdish',
  	'lo': 'Lao - Tiếng Lào',
  	'lao': 'Lao - Tiếng Lào',
  	'la': 'Latin - Tiếng La-tinh',
  	'lat': 'Latin - Tiếng La-tinh',
  	'lv': 'Latvian - Tiếng Latvia',
  	'lav': 'Latvian - Tiếng Latvia',
  	'li': 'Limburgan; Limburger; Limburgish',
  	'lim': 'Limburgan; Limburger; Limburgish',
  	'ln': 'Lingala',
  	'lin': 'Lingala',
  	'lt': 'Lithuanian - Tiếng Lithuania',
  	'lit': 'Lithuanian - Tiếng Lithuania',
  	'lb': 'Luxembourgish; Letzeburgesch',
  	'ltz': 'Luxembourgish; Letzeburgesch',
  	'mk': 'Macedonian',
  	'mac/mkd*': 'Macedonian',
  	'mg': 'Malagasy',
  	'mlg': 'Malagasy',
  	'ms': 'Malay - Tiếng Mã Lai',
  	'may/msa*': 'Malay - Tiếng Mã Lai',
  	'ml': 'Malayalam',
  	'mal': 'Malayalam',
  	'mt': 'Maltese',
  	'mlt': 'Maltese',
  	'gv': 'Manx',
  	'glv': 'Manx',
  	'mi': 'Maori',
  	'mao/mri*': 'Maori',
  	'mr': 'Marathi - Tiếng Marath',
  	'mar': 'Marathi - Tiếng Marath',
  	'mh': 'Marshallese',
  	'mah': 'Marshallese',
  	'mo': 'Moldavian',
  	'mol': 'Moldavian',
  	'mn': 'Mongolian - Tiếng Mông Cổ',
  	'mon': 'Mongolian - Tiếng Mông Cổ',
  	'na': 'Nauru',
  	'nau': 'Nauru',
  	'nv': 'Navaho, Navajo',
  	'nav': 'Navaho, Navajo',
  	'nd': 'Ndebele, North',
  	'nde': 'Ndebele, North',
  	'nr': 'Ndebele, South',
  	'nbl': 'Ndebele, South',
  	'ng': 'Ndonga',
  	'ndo': 'Ndonga',
  	'ne': 'Nepali - Tiếng Nepal',
  	'nep': 'Nepali - Tiếng Nepal',
  	'se': 'Northern Sami',
  	'sme': 'Northern Sami',
  	'no': 'Norwegian - Tiếng Na Uy',
  	'nor': 'Norwegian - Tiếng Na Uy',
  	'nb': 'Norwegian Bokmal',
  	'nob': 'Norwegian Bokmal',
  	'nn': 'Norwegian Nynorsk',
  	'nno': 'Norwegian Nynorsk',
  	'ny': 'Nyanja; Chichewa; Chewa',
  	'nya': 'Nyanja; Chichewa; Chewa',
  	'oc': 'Occitan (post 1500); Provencal',
  	'oci': 'Occitan (post 1500); Provencal',
  	'or': 'Oriya',
  	'ori': 'Oriya',
  	'om': 'Oromo',
  	'orm': 'Oromo',
  	'os': 'Ossetian; Ossetic',
  	'oss': 'Ossetian; Ossetic',
  	'pi': 'Pali',
  	'pli': 'Pali',
  	'pa': 'Panjabi',
  	'pan': 'Panjabi',
  	'fa': 'Persian - Tiếng Ba Tư',
  	'per/fas*': 'Persian - Tiếng Ba Tư',
  	'pl': 'Polish - Tiếng Ba Lan',
  	'pol': 'Polish - Tiếng Ba Lan',
  	'pt': 'Portuguese - Tiếng Bồ Đào Nha',
  	'por': 'Portuguese - Tiếng Bồ Đào Nha',
  	'ps': 'Pushto',
  	'pus': 'Pushto',
  	'qu': 'Quechua',
  	'que': 'Quechua',
  	'rm': 'Raeto-Romance',
  	'roh': 'Raeto-Romance',
  	'ro': 'Romanian - Tiếng Romania',
  	'rum/ron*': 'Romanian - Tiếng Romania',
  	'rn': 'Rundi',
  	'run': 'Rundi',
  	'ru': 'Russian - Tiếng Nga',
  	'rus': 'Russian - Tiếng Nga',
  	'sm': 'Samoan',
  	'smo': 'Samoan',
  	'sg': 'Sango',
  	'sag': 'Sango',
  	'sa': 'Sanskrit',
  	'san': 'Sanskrit',
  	'sc': 'Sardinian',
  	'srd': 'Sardinian',
  	'sr': 'Serbian - Tiếng Serbia',
  	'scc/srp*': 'Serbian - Tiếng Serbia',
  	'sn': 'Shona',
  	'sna': 'Shona',
  	'ii': 'Sichuan Yi',
  	'iii': 'Sichuan Yi',
  	'sd': 'Sindhi',
  	'snd': 'Sindhi',
  	'si': 'Sinhala; Sinhalese',
  	'sin': 'Sinhala; Sinhalese',
  	'sk': 'Slovak - Tiếng Slovak',
  	'slo/slk*': 'Slovak - Tiếng Slovak',
  	'sl': 'Slovenian - Tiếng Slovene',
  	'slv': 'Slovenian - Tiếng Slovene',
  	'so': 'Somali - Tiếng Somalia',
  	'som': 'Somali - Tiếng Somalia',
  	'st': 'Sotho, Southern',
  	'sot': 'Sotho, Southern',
  	'es': 'Spanish; Castilian - Tiếng Tây Ban Nha',
  	'spa': 'Spanish; Castilian - Tiếng Tây Ban Nha',
  	'su': 'Sundanese',
  	'sun': 'Sundanese',
  	'sw': 'Swahili - Tiếng Swahili',
  	'swa': 'Swahili - Tiếng Swahili',
  	'ss': 'Swati',
  	'ssw': 'Swati',
  	'sv': 'Swedish - Tiếng Thụy Điển',
  	'swe': 'Swedish - Tiếng Thụy Điển',
  	'tl': 'Tagalog - Tiếng Tagalog',
  	'tgl': 'Tagalog - Tiếng Tagalog',
  	'ty': 'Tahitian',
  	'tah': 'Tahitian',
  	'tg': 'Tajik',
  	'tgk': 'Tajik',
  	'ta': 'Tamil - Tiếng Tamil',
  	'tam': 'Tamil - Tiếng Tamil',
  	'tt': 'Tatar',
  	'tat': 'Tatar',
  	'te': 'Telugu - Tiếng Telugu',
  	'tel': 'Telugu - Tiếng Telugu',
  	'th': 'Thai - Tiếng Thái',
  	'tha': 'Thai - Tiếng Thái',
  	'bo': 'Tibetan',
  	'tib/bod*': 'Tibetan',
  	'ti': 'Tigrinya',
  	'tir': 'Tigrinya',
  	'to': 'Tonga (Tonga Islands)',
  	'ton': 'Tonga (Tonga Islands)',
  	'ts': 'Tsonga',
  	'tso': 'Tsonga',
  	'tn': 'Tswana',
  	'tsn': 'Tswana',
  	'tr': 'Turkish - Tiếng Thổ Nhĩ Kỳ',
  	'tur': 'Turkish - Tiếng Thổ Nhĩ Kỳ',
  	'tk': 'Turkmen',
  	'tuk': 'Turkmen',
  	'tw': 'Twi',
  	'twi': 'Twi',
  	'ug': 'Uighur',
  	'uig': 'Uighur',
  	'uk': 'Ukrainian - Tiếng Ukraina',
  	'ukr': 'Ukrainian - Tiếng Ukraina',
  	'ur': 'Urdu - Tiếng Urdu',
  	'urd': 'Urdu - Tiếng Urdu',
  	'uz': 'Uzbek - Tiếng Uzbek',
  	'uzb': 'Uzbek - Tiếng Uzbek',
  	'vi': 'Vietnamese - Tiếng Việt',
  	'vie': 'Vietnamese - Tiếng Việt',
  	'vo': 'Volapuk',
  	'vol': 'Volapuk',
  	'wa': 'Walloon',
  	'wln': 'Walloon',
  	'cy': 'Welsh - Tiếng Wales',
  	'wel/cym*': 'Welsh - Tiếng Wales',
  	'fy': 'Western Frisian',
  	'fry': 'Western Frisian',
  	'wo': 'Wolof',
  	'wol': 'Wolof',
  	'xh': 'Xhosa',
  	'xho': 'Xhosa',
  	'yi': 'Yiddish',
  	'yid': 'Yiddish',
  	'yo': 'Yoruba',
  	'yor': 'Yoruba',
  	'za': 'Zhuang; Chuang',
  	'zha': 'Zhuang; Chuang',
  	'zu': 'Zulu - Tiếng Zulu',
  	'zul': 'Zulu - Tiếng Zulu'
  }
    text = (request.form.get('text'))


    language_code = detect(text)
    sentence = [all_languages_codes.get(language_code), language_code, text]
    final = '{:24}'.format(*sentence)
    print(final)

    return render_template('index.html',text=text,ans=final)

#  main
if __name__ == '__main__':

	app.run(debug=True)